backend:
  name: github
  repo: enjoythevue/website

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "episodes"
    label: "Episodes"
    folder: "episodes"
    create: true
    slug: "{{slug}}"
    identifier_field: episode-number
    fields:
      - {label: "Episode number", name: "episode-number", widget: "number"}
      - {label: "Episode title", name: "episode-title", widget: "string"}
      - {label: "Date published", name: "date-published", widget: "datetime"}
      - {label: "Cover art", name: "cover-art", widget: "image"}
      - {label: "Sharing link", name: "sharing-link", widget: "string"}
      - {label: "RSS link", name: "rss-link", widget: "string"}
      - {label: "Download link", name: "download-link", widget: "string"}
      - label: "Sponsorship details"
        name: "sponsorship-details"
        widget: "object"
        fields: 
          - {label: "Sponsor name", name: "sponsor-name", widget: "string"}
          - {label: "Sponsor logo", name: "sponsor-logo", widget: "image"}
          - {label: "Offer details", name: "sponsor-offer-details", widget: "markdown"}
          - {label: "Offer code", name: "sponsor-offer-code", widget: "string"}
      - label: "Picks"
        name: "picks"
        widget: "object"
        fields: 
          - {label: "Chris picks", name: "chris-picks", widget: "markdown"}
          - {label: "Ben picks", name: "ben-picks", widget: "markdown"}
          - {label: "Ari picks", name: "ari-picks", widget: "markdown"}
          - {label: "Elizabeth picks", name: "elizabeth-picks", widget: "markdown"}
      - {label: "Shownotes", name: "shownotes", widget: "markdown"}
      - {label: "Transcript", name: "transcript", widget: "markdown"}




      